"""add_missing_tables

Revision ID: 8754907c019f
Revises: 0a06619cd7eb
Create Date: 2025-05-18 19:17:52.966326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8754907c019f'
down_revision: Union[str, None] = '0a06619cd7eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_portfolio_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('total_cost_basis', sa.Float(), nullable=False),
    sa.Column('total_profit_loss', sa.Float(), nullable=False),
    sa.Column('total_profit_loss_percentage', sa.Float(), nullable=False),
    sa.Column('crypto_value', sa.Float(), nullable=False),
    sa.Column('stable_value', sa.Float(), nullable=False),
    sa.Column('daily_change', sa.Float(), nullable=True),
    sa.Column('weekly_change', sa.Float(), nullable=True),
    sa.Column('monthly_change', sa.Float(), nullable=True),
    sa.Column('assets', sa.JSON(), nullable=True),
    sa.Column('trades_today', sa.Integer(), nullable=True),
    sa.Column('swaps_today', sa.Integer(), nullable=True),
    sa.Column('realized_profit_today', sa.Float(), nullable=True),
    sa.Column('market_trend', sa.String(length=10), nullable=True),
    sa.Column('market_volatility', sa.Float(), nullable=True),
    sa.Column('is_hedged', sa.Boolean(), nullable=True),
    sa.Column('risk_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['telegram_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_portfolio_summary_id'), 'user_portfolio_summary', ['id'], unique=False)
    op.create_index(op.f('ix_user_portfolio_summary_timestamp'), 'user_portfolio_summary', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_portfolio_summary_timestamp'), table_name='user_portfolio_summary')
    op.drop_index(op.f('ix_user_portfolio_summary_id'), table_name='user_portfolio_summary')
    op.drop_table('user_portfolio_summary')
    op.drop_table('transactions')
    # ### end Alembic commands ###
